/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#556346',
        'primary-dim': '#49573a',
        'primary-container': '#d8e8c3',
        'on-primary': '#edfdd7',
        'on-primary-container': '#48563a',
        secondary: '#78604b',
        'secondary-dim': '#6b5440',
        'secondary-container': '#fddcc3',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#644d3a',
        tertiary: '#716252',
        'tertiary-dim': '#645647',
        'tertiary-container': '#fde7d3',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#635445',
        background: '#fffcf7',
        'on-background': '#383831',
        surface: '#fffcf7',
        'surface-bright': '#fffcf7',
        'surface-dim': '#e4e3d7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fcf9f3',
        'surface-container': '#f6f4ec',
        'surface-container-high': '#f0eee5',
        'surface-container-highest': '#eae8de',
        'surface-variant': '#eae8de',
        'on-surface': '#383831',
        'on-surface-variant': '#65655c',
        outline: '#818178',
        'outline-variant': '#babab0',
        error: '#a54731',
        'error-container': '#fe8b70',
        'on-error': '#ffffff',
        'inverse-surface': '#0e0e0c',
        'inverse-on-surface': '#9e9d98',
        'inverse-primary': '#e9f9d3',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'serif'],
        body: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      boxShadow: {
        'ambient': '0 40px 60px -15px rgba(56,56,49,0.06)',
        'ambient-lg': '0 40px 60px -15px rgba(56,56,49,0.08)',
      },
    },
  },
  plugins: [],
}
